[project]
name = "sevadeep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SohamPhansalkar", email = "sohampp26nov@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pymysql>=1.2.3",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[project.scripts]
sevadeep = "sevadeep:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
